name: Test Action for Service A
on:
  paths:
    - "service-a/**"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Run test for Service A"
      - run: echo "🍏 This job's status is ${{ job.status }}."

name: Test Action for Service B
on:
  paths:
    - "service-b/**"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Run test for Service B"
      - run: echo "🍏 This job's status is ${{ job.status }}."